name = "Product Chatbot"

uid = "ce317f14-cff3-49c8-23a9-c805e96f49e1de6dce8b"

type = "theme_app_extension"
extension_type = "theme_app_extension"

[[extensions]]
type = "theme_app_extension"
handle = "product-chatbot"
name = "Product Chatbot"

[capabilities]
block_progress = true

[[metafields]]
namespace = "product-chatbot"
key = "settings"